- hosts: mysql
  tasks:
  - name: Add mysql repo
    yum: name=http://dev.mysql.com/get/mysql80-community-release-el7-1.noarch.rpm state=present

  - name: Install MySQL
    yum: name="mysql-community-server"

  - name: start services
    service: name=mysqld state=started enabled=yes
